services:
  - type: web
    name: consensus-api
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        fromDatabase:
          name: consensus-db
          property: connectionString
      - key: FRONTEND_URL
        value: http://localhost:3000
